name: fluid_background
description: "A new Flutter package project."
version: 1.0.0
homepage: https://github.com/Diaglyonok/fluid_background

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0